### ISSUE TITLE
Scripts to generate .PT data files

### ISSUE THREAD

**Issue by ruisi-su** [Yinghao-Li/GuiGen#1]
Hi,

I happened to read this paper a couple of weeks ago and found this idea really fascinating! I started trying out the code and I was wondering if you could please share the code to generate the .pt data (the URL mentioned in the README). For example, did you read separate files for text strings and syntax strings?

Thanks in advance!

**Comment by Yinghao-Li** [comment]
Hi, I'm not feeling well these days. I'll look into it later.

**Comment by ruisi-su** [comment]
> Hi, I'm not feeling well these days. I'll look into it later.

No problem, hope you feel better soon!

**Comment by Yinghao-Li** [comment]
Hi,

I checked my local projects. Unfortunately, it seems that all the source code of this project is lost except for this GitHub repo. As it has been a long time since the last time I attend this project, I can only share some high-level concepts of generating the data.

The data come from Iyyer [2018](https://aclanthology.org/N18-1170/), as mentioned in the paper. I used AllenNLP to generate the constituency parse trees. The levels of tree nodes are calculated by counting the parenthesis. I don't remember if I put text and syntax strings in the same file or not, but I believe it does not matter. You can modify [this function](https://github.com/Yinghao-Li/GuiGen/blob/22ababcd8cacae0adcc4ee74b514b188dc5084f3/txt_gen_train.py#L162) and the corresponding arguments to make the model accommodate your data format.

Don't hesitate to ask if there's anything that is not clear or does not make sense to you.
